apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: numb4r/node-app
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: url_shortener_db
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: PORT
          value: "80"
        ports:
          - containerPort: 80
      nodeSelector:
        finality: app
